name: pdf_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:

  syncfusion_flutter_pdfviewer: ^20.1.48-beta.1
  flutter_pdfview: ^1.2.1

cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/pdf/
  #   - images/a_dot_ham.jpeg

